[package]
authors                = ["Procivis"]
edition.workspace      = true
license                = "Apache-2.0"
name                   = "sql-data-provider"
publish                = false
rust-version.workspace = true
version.workspace      = true

[features]
mysql      = ["migration/mysql", "sea-orm/sqlx-mysql"]
postgres   = ["migration/postgres", "sea-orm/sqlx-postgres"]
test_utils = ["dep:similar-asserts"]
# Treat build warnings as error
strict = []

[dependencies]
anyhow.workspace             = true
async-trait.workspace        = true
autometrics.workspace        = true
futures                      = { version = "0.3" }
hex.workspace                = true
itertools.workspace          = true
migration.workspace          = true
one-core.workspace           = true
one-dto-mapper.workspace     = true
sea-orm                      = { workspace = true, features = ["sqlx-sqlite", "runtime-tokio", "macros", "with-time", "with-json"] }
serde.workspace              = true
serde_json.workspace         = true
serde_with.workspace         = true
shared-types.workspace       = true
similar-asserts              = { workspace = true, optional = true }
standardized-types.workspace = true
time.workspace               = true
tokio                        = { workspace = true, features = ["macros"] }
tracing.workspace            = true
url                          = { workspace = true }
uuid                         = { workspace = true, features = ["serde"] }

[dev-dependencies]
assert2.workspace         = true
futures.workspace         = true
mockall.workspace         = true
one-core                  = { workspace = true, features = ["mock"] }
similar-asserts.workspace = true
tempfile.workspace        = true

[lints]
workspace = true
