use anyhow::anyhow;
use autometrics::autometrics;
use futures::FutureExt;
use one_core::model::proof_schema::{
    GetProofSchemaList, ProofInputSchema, ProofSchema, ProofSchemaListQuery,
};
use one_core::repository::error::{DataLayerError, EntityKind};
use one_core::repository::proof_schema_repository::ProofSchemaRepository;
use sea_orm::{
    ActiveModelTrait, ColumnTrait, EntityTrait, QueryFilter, QueryOrder, Set, Unchanged,
};
use shared_types::ProofSchemaId;
use time::OffsetDateTime;

use super::ProofSchemaProvider;
use super::mapper::proof_schema_from_models;
use crate::common::list_query_with_custom_model;
use crate::entity::{proof_input_claim_schema, proof_input_schema, proof_schema};
use crate::list_query_generic::SelectWithListQuery;
use crate::mapper::{to_data_layer_error, to_update_data_layer_error};

#[autometrics]
#[async_trait::async_trait]
impl ProofSchemaRepository for ProofSchemaProvider {
    async fn create_proof_schema(
        &self,
        request: ProofSchema,
    ) -> Result<ProofSchemaId, DataLayerError> {
        let proof_schema_id = request.id;
        let proof_schema = proof_schema::ActiveModel::from(&request);

        let proof_input_schemas = request.input_schemas.as_ref().await?;
        if proof_input_schemas.is_empty() {
            return Err(DataLayerError::IncorrectParameters);
        }

        let now = one_core::clock::now_utc();
        let proof_input_schemas_active_model: Vec<_> = proof_input_schemas
            .iter()
            .enumerate()
            .map(|(order, schema)| proof_input_schema::ActiveModel {
                order: Set(order as _),
                created_date: Set(now),
                last_modified: Set(now),
                credential_schema: Set(schema.credential_schema.id()),
                proof_schema: Set(proof_schema_id),
                ..Default::default()
            })
            .collect();

        let proof_input_schemas_with_order: Vec<(u32, &ProofInputSchema)> =
            proof_input_schemas_active_model
                .iter()
                .zip(&proof_input_schemas)
                .map(|(p1, p2)| (*p1.order.as_ref() as u32, p2))
                .collect();

        let action = async {
            proof_schema
                .insert(&self.db)
                .await
                .map_err(to_data_layer_error)?;

            proof_input_schema::Entity::insert_many(proof_input_schemas_active_model)
                .exec(&self.db)
                .await
                .map_err(|err| DataLayerError::Db(err.into()))?;

            // we need proof_input_schema's id to construct the proof_input_claim_schema record
            // but this id is generated by the db when inserted so we need to fetch what we just inserted
            let retrieved_proof_input_schema = proof_input_schema::Entity::find()
                .filter(proof_input_schema::Column::ProofSchema.eq(proof_schema_id.to_string()))
                .all(&self.db)
                .await
                .map_err(|err| DataLayerError::Db(err.into()))?;

            if retrieved_proof_input_schema.len() != proof_input_schemas_with_order.len() {
                return Err(DataLayerError::Db(anyhow!(
                    "Length of retrieved proof input schemas is different from the proof input schemas in the request for proof schema: {proof_schema_id}"
                )));
            }

            let mut retrieved_proof_input_schema = retrieved_proof_input_schema;
            retrieved_proof_input_schema.sort_by_key(|k| k.order);

            let mut proof_input_schemas = proof_input_schemas_with_order;
            proof_input_schemas.sort_by_key(|(order, _)| *order);

            let mut proof_input_claim_schemas = vec![];
            for (model, (order, request)) in retrieved_proof_input_schema
                .into_iter()
                .zip(proof_input_schemas)
            {
                if model.credential_schema != request.credential_schema.id()
                    || order != model.order as u32
                {
                    return Err(DataLayerError::Db(anyhow!(
                        "Inserted proof input schema model doesn't match request proof input schema for proof schema: {proof_schema_id}"
                    )));
                }

                let claim_schemas = request.claim_schemas.as_ref().await?;

                for (order, claim_schema) in claim_schemas.iter().enumerate() {
                    let schema = proof_input_claim_schema::ActiveModel {
                        claim_schema_id: Set(claim_schema.schema.id),
                        proof_input_schema_id: Set(model.id),
                        order: Set(order as _),
                        required: Set(claim_schema.required),
                    };

                    proof_input_claim_schemas.push(schema)
                }
            }
            proof_input_claim_schema::Entity::insert_many(proof_input_claim_schemas)
                .exec(&self.db)
                .await
                .map_err(|err| DataLayerError::Db(err.into()))?;
            Ok::<_, DataLayerError>(())
        }.boxed();
        self.db.tx(action).await??;
        Ok(proof_schema_id)
    }

    async fn get_proof_schema(&self, id: &ProofSchemaId) -> Result<ProofSchema, DataLayerError> {
        let proof_schema_model = crate::entity::proof_schema::Entity::find_by_id(id)
            .one(&self.db)
            .await
            .map_err(|e| DataLayerError::Db(e.into()))?
            .ok_or_else(|| DataLayerError::EntityNotFound {
                kind: EntityKind::ProofSchema,
                id: (*id).into(),
            })?;

        Ok(proof_schema_from_models(
            proof_schema_model,
            &self.db,
            &self.organisation_repository,
            &self.credential_schema_repository,
            &self.claim_schema_repository,
        ))
    }

    async fn get_proof_schema_list(
        &self,
        query_params: ProofSchemaListQuery,
    ) -> Result<GetProofSchemaList, DataLayerError> {
        let query = crate::entity::proof_schema::Entity::find()
            .filter(proof_schema::Column::DeletedAt.is_null())
            .with_list_query(&query_params)
            .order_by_desc(proof_schema::Column::CreatedDate)
            .order_by_desc(proof_schema::Column::Id);

        list_query_with_custom_model(query, query_params, &self.db, |model| {
            Ok(proof_schema_from_models(
                model,
                &self.db,
                &self.organisation_repository,
                &self.credential_schema_repository,
                &self.claim_schema_repository,
            ))
        })
        .await
    }

    async fn delete_proof_schema(
        &self,
        id: &ProofSchemaId,
        deleted_at: OffsetDateTime,
    ) -> Result<(), DataLayerError> {
        let schema = proof_schema::ActiveModel {
            id: Unchanged(*id),
            deleted_at: Set(Some(deleted_at)),
            ..Default::default()
        };

        proof_schema::Entity::update(schema)
            .filter(proof_schema::Column::DeletedAt.is_null())
            .exec(&self.db)
            .await
            .map_err(to_update_data_layer_error)?;

        Ok(())
    }
}
