format: {}
identifier: {}
issuanceProtocol: {}
verificationProtocol: {}
revocation: {}
did: {}
keyAlgorithm: {}
keyStorage: {}
datatype: {}
task: {}
transport: {}
cacheEntities: {}
blobStorage: {}
walletProvider: {}
credentialIssuer: {}
verificationEngagement: {}
signer: {}
verifierProvider: {}
keySecurityLevel: {}
trustListPublisher: {}
trustListSubscriber: {}
documentSignerProvider: {}
transactionDataProvider: {}
globalSettings: {}
