[package]
authors                = ["Procivis"]
edition.workspace      = true
license                = "Apache-2.0"
name                   = "migration"
publish                = false
rust-version.workspace = true
version                = "0.1.0"

[dependencies]
sea-orm               = { workspace = true, features = ["with-time", "with-uuid"] }
sea-orm-migration     = { version = "1.1", default-features = false, features = ["runtime-tokio", "sqlx-sqlite"] }
serde.workspace       = true
serde_json.workspace  = true
serde_with.workspace  = true
shared-types          = { workspace = true, features = ["sea-orm"] }
time.workspace        = true
tokio                 = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing.workspace     = true
urlencoding.workspace = true
uuid                  = { workspace = true, features = ["v4"] }

[features]
mysql    = ["sea-orm-migration/sqlx-mysql"]
postgres = ["sea-orm-migration/sqlx-postgres"]

[dev-dependencies]
regex.workspace = true
sea-schema = { version = "0.17.0-rc.16", default-features = false, features = [
    "discovery",
    "sqlite",
    "postgres",
    "sqlx-postgres",
    "sqlx-sqlite",
    "mysql",
    "sqlx-mysql",
    "runtime-tokio",
] }
similar-asserts.workspace = true
ulid.workspace = true
url.workspace = true

[lints]
workspace = true
