[package]
authors.workspace      = true
edition.workspace      = true
license.workspace      = true
name                   = "standardized-types"
rust-version.workspace = true
version.workspace      = true

[dependencies]
anyhow.workspace         = true
bon.workspace            = true
ct-codecs.workspace      = true
indexmap.workspace       = true
one-dto-mapper.workspace = true
proc-macros.workspace    = true
quick-xml.workspace      = true
secrecy.workspace        = true
serde                    = { workspace = true, features = ["derive"] }
serde_json.workspace     = true
serde_with.workspace     = true
strum.workspace          = true
time.workspace           = true
thiserror.workspace      = true
url.workspace            = true
utoipa                   = { workspace = true, optional = true }
uuid.workspace           = true

[features]
utoipa = ["dep:utoipa", "utoipa/indexmap", "utoipa/url"]

[dev-dependencies]
serde_urlencoded.workspace = true
similar-asserts.workspace  = true

[lints]
workspace = true
