use std::sync::Arc;

use indexmap::IndexMap;
use one_crypto::utilities::{generate_alphanumeric, generate_numeric};
use shared_types::{BlobId, DidMethodId, IdentifierId};
use standardized_types::openid4vci::{ProofTypeSupported, TxCodeInputMode};
use time::OffsetDateTime;
use uuid::Uuid;

use crate::config::core_config::KeyAlgorithmType;
use crate::error::ContextWithErrorCode;
use crate::model::credential::{Clearable, CredentialStateEnum, UpdateCredentialRequest};
use crate::model::credential_schema::{TransactionCode, TransactionCodeType};
use crate::model::interaction::{Interaction, InteractionType};
use crate::model::key::Key;
use crate::model::organisation::Organisation;
use crate::model::relation::Related;
use crate::proto::identifier_creator::{CreateLocalIdentifierRequest, IdentifierCreator};
use crate::provider::did_method::DidKeys;
use crate::provider::did_method::model::Operation;
use crate::provider::did_method::provider::DidMethodProvider;
use crate::provider::issuance_protocol::HolderBindingInput;
use crate::provider::issuance_protocol::error::IssuanceProtocolError;
use crate::provider::key_algorithm::provider::KeyAlgorithmProvider;
use crate::provider::key_security_level::provider::KeySecurityLevelProvider;
use crate::provider::key_storage::KeyStorage;
use crate::provider::key_storage::provider::KeyProvider;
use crate::repository::key_repository::KeyRepository;
use crate::service::did::dto::{CreateDidRequestDTO, CreateDidRequestKeysDTO};

pub(super) fn get_issued_credential_update(
    credential_blob_id: BlobId,
    holder_identifier_id: IdentifierId,
) -> UpdateCredentialRequest {
    UpdateCredentialRequest {
        state: Some(CredentialStateEnum::Accepted),
        suspend_end_date: Clearable::DontTouch,
        holder_identifier_id: Some(holder_identifier_id),
        credential_blob_id: Some(credential_blob_id),
        ..Default::default()
    }
}

pub(crate) fn interaction_from_handle_invitation(
    data: Option<Vec<u8>>,
    now: OffsetDateTime,
    organisation: impl Into<Related<Organisation>>,
) -> Interaction {
    Interaction {
        id: Uuid::new_v4().into(),
        created_date: now,
        last_modified: now,
        data,
        organisation: organisation.into(),
        nonce_id: None,
        interaction_type: InteractionType::Issuance,
        expires_at: None,
    }
}

#[expect(clippy::too_many_arguments)]
pub(super) async fn autogenerate_holder_binding(
    cryptographic_binding_methods_supported: Option<&Vec<String>>,
    proof_types_supported: Option<&IndexMap<String, ProofTypeSupported>>,
    organisation: &Organisation,
    key_provider: &dyn KeyProvider,
    key_algorithm_provider: &dyn KeyAlgorithmProvider,
    key_security_level_provider: &dyn KeySecurityLevelProvider,
    did_method_provider: &dyn DidMethodProvider,
    key_repository: &dyn KeyRepository,
    identifier_creator: &dyn IdentifierCreator,
) -> Result<HolderBindingInput, IssuanceProtocolError> {
    let PickedKeyConfig {
        key_storage_id,
        key_storage,
        key_algorithm,
    } = pick_key_configuration(
        proof_types_supported,
        key_provider,
        key_algorithm_provider,
        key_security_level_provider,
    )?;

    let key_id = Uuid::new_v4().into();
    let key = key_storage
        .generate(key_id, key_algorithm, serde_json::json!({}))
        .await
        .map_err(|e| IssuanceProtocolError::BindingAutogenerationFailure(e.to_string()))?;

    let now = crate::clock::now_utc();
    let key = Key {
        id: key_id,
        created_date: now,
        last_modified: now,
        public_key: key.public_key,
        name: format!("autogenerated-{key_id}"),
        key_reference: key.key_reference,
        storage_type: key_storage_id,
        key_type: key_algorithm.to_string(),
        organisation: organisation.to_owned().into(),
    };
    key_repository
        .create_key(key.to_owned())
        .await
        .map_err(|e| IssuanceProtocolError::BindingAutogenerationFailure(e.to_string()))?;

    // generate did only if jwk/cose_key binding method is not supported by the issuer
    if let Some(methods) = cryptographic_binding_methods_supported
        && !methods.contains(&"jwk".to_string())
        && !methods.contains(&"cose_key".to_string())
    {
        return generate_holder_binding_did(
            methods,
            key,
            organisation,
            did_method_provider,
            identifier_creator,
        )
        .await;
    };

    let identifier = identifier_creator
        .create_local_identifier(
            format!("autogenerated-key-{}", key.id),
            CreateLocalIdentifierRequest::Key(key.to_owned()),
            organisation.to_owned(),
        )
        .await
        .map_err(|e| IssuanceProtocolError::BindingAutogenerationFailure(e.to_string()))?;

    Ok(HolderBindingInput { identifier, key })
}

async fn generate_holder_binding_did(
    cryptographic_binding_methods_supported: &[String],
    key: Key,
    organisation: &Organisation,
    did_method_provider: &dyn DidMethodProvider,
    identifier_creator: &dyn IdentifierCreator,
) -> Result<HolderBindingInput, IssuanceProtocolError> {
    let did_method = select_did_method(
        cryptographic_binding_methods_supported,
        &key,
        did_method_provider,
    )?;

    let key_id = key.id;
    let name = format!("autogenerated-did-{key_id}");
    let identifier = identifier_creator
        .create_local_identifier(
            name.to_owned(),
            CreateLocalIdentifierRequest::Did(CreateDidRequestDTO {
                name,
                organisation_id: organisation.id,
                did_method,
                keys: CreateDidRequestKeysDTO {
                    authentication: vec![key_id],
                    assertion_method: vec![key_id],
                    key_agreement: vec![key_id],
                    capability_invocation: vec![key_id],
                    capability_delegation: vec![key_id],
                },
                params: None,
            }),
            organisation.to_owned(),
        )
        .await
        .map_err(|e| IssuanceProtocolError::BindingAutogenerationFailure(e.to_string()))?;

    Ok(HolderBindingInput { identifier, key })
}

fn select_did_method(
    cryptographic_binding_methods_supported: &[String],
    key: &Key,
    did_method_provider: &dyn DidMethodProvider,
) -> Result<DidMethodId, IssuanceProtocolError> {
    for method_name in did_method_provider.supported_method_names() {
        // do not try to autogenerate a did:webvh or did:web for holder binding
        if method_name == "webvh" || method_name == "tdw" || method_name == "web" {
            continue;
        }

        if !cryptographic_binding_methods_supported.contains(&format!("did:{method_name}")) {
            continue;
        }

        let (did_method_id, did_method) = did_method_provider
            .get_did_method_by_method_name(&method_name)
            .error_while("resolving did method")?;

        let capabilities = did_method.get_capabilities();
        if !capabilities.operations.contains(&Operation::CREATE) {
            continue;
        }
        if !capabilities.key_algorithms.contains(
            &key.key_algorithm_type()
                .error_while("parsing key algorithm")?,
        ) {
            continue;
        }

        if let Some(key_limits) = did_method.get_keys()
            && !key_limits.validate_keys(&DidKeys {
                authentication: vec![key.clone()],
                assertion_method: vec![key.clone()],
                key_agreement: vec![key.clone()],
                capability_invocation: vec![key.clone()],
                capability_delegation: vec![key.clone()],
                update_keys: None,
            })
        {
            continue;
        }

        return Ok(did_method_id);
    }

    Err(IssuanceProtocolError::BindingAutogenerationFailure(
        format!(
            "No supported DID method, cryptographic_binding_methods_supported: [{}]",
            cryptographic_binding_methods_supported.join(", ")
        ),
    ))
}

struct PickedKeyConfig {
    key_storage_id: String,
    key_storage: Arc<dyn KeyStorage>,
    key_algorithm: KeyAlgorithmType,
}

fn pick_key_configuration(
    proof_types_supported: Option<&IndexMap<String, ProofTypeSupported>>,
    key_provider: &dyn KeyProvider,
    key_algorithm_provider: &dyn KeyAlgorithmProvider,
    key_security_level_provider: &dyn KeySecurityLevelProvider,
) -> Result<PickedKeyConfig, IssuanceProtocolError> {
    let issuer_proof_config = proof_types_supported
        .as_ref()
        .and_then(|proof_types| proof_types.get("jwt"));

    let issuer_accepted_key_storage_security_levels = issuer_proof_config
        .and_then(|proof_type| {
            proof_type
                .key_attestations_required
                .as_ref()
                .map(|kar| &kar.key_storage)
        })
        .and_then(|levels| (!levels.is_empty()).then_some(levels));

    let issuer_accepted_algorithms = issuer_proof_config.map(|proof_type| {
        proof_type
            .proof_signing_alg_values_supported
            .iter()
            .filter_map(|alg| key_algorithm_provider.key_algorithm_from_jose_alg(alg))
            .map(|(alg, _)| alg)
            .collect::<Vec<_>>()
    });

    for (_, security_level) in key_security_level_provider.ordered_by_priority() {
        if issuer_accepted_key_storage_security_levels
            .as_ref()
            .is_some_and(|issuer_accepted_levels| {
                !security_level
                    .get_capabilities()
                    .openid_security_level
                    .iter()
                    .any(|level| issuer_accepted_levels.contains(level))
            })
        {
            continue;
        }

        for key_storage_id in security_level.get_key_storages() {
            let storage = key_provider.get_key_storage(key_storage_id)?;

            for (algorithm, _) in key_algorithm_provider.ordered_by_holder_priority() {
                if !storage.get_capabilities().algorithms.contains(&algorithm) {
                    continue;
                }

                if let Some(issuer_accepted_algorithms) = &issuer_accepted_algorithms
                    && !issuer_accepted_algorithms.contains(&algorithm)
                {
                    continue;
                }

                return Ok(PickedKeyConfig {
                    key_storage_id: key_storage_id.to_owned(),
                    key_storage: storage,
                    key_algorithm: algorithm,
                });
            }
        }
    }

    Err(IssuanceProtocolError::BindingAutogenerationFailure(
        format!(
            "Could not find a proper key storage, issuer_accepted_key_storage_security_levels:{issuer_accepted_key_storage_security_levels:?}, issuer_accepted_algorithms:{issuer_accepted_algorithms:?}"
        ),
    ))
}

impl From<TxCodeInputMode> for TransactionCodeType {
    fn from(value: TxCodeInputMode) -> Self {
        match value {
            TxCodeInputMode::Numeric => Self::Numeric,
            TxCodeInputMode::Text => Self::Alphanumeric,
        }
    }
}

impl From<TransactionCodeType> for TxCodeInputMode {
    fn from(value: TransactionCodeType) -> Self {
        match value {
            TransactionCodeType::Numeric => Self::Numeric,
            TransactionCodeType::Alphanumeric => Self::Text,
        }
    }
}

pub(crate) fn generate_transaction_code(prescription: &TransactionCode) -> String {
    match prescription.r#type {
        TransactionCodeType::Numeric => generate_numeric(prescription.length as _),
        TransactionCodeType::Alphanumeric => generate_alphanumeric(prescription.length as _),
    }
}
