[package]
authors                = ["Procivis"]
build                  = "build.rs"
edition.workspace      = true
license                = "Apache-2.0"
name                   = "core-server"
publish                = false
rust-version.workspace = true
version                = "0.1.0"

# disable doctests
[lib]
doctest = false

[features]
# Treat build warnings as error
strict = []

[dependencies]
axum = { version = "0.8", features = ["macros"] }
axum-extra = { version = "0.12", features = ["typed-header", "with-rejection"] }
clap.workspace = true
ct-codecs.workspace = true
futures.workspace = true
headers = { version = "0.4" }
http-body-util = "0.1.2"
indexmap.workspace = true
indoc.workspace = true
mime.workspace = true
one-core = { workspace = true, features = ["config_json", "config_yaml", "config_env"] }
one-crypto.workspace = true
one-dto-mapper.workspace = true
proc-macros.workspace = true
prometheus = { version = "0.14", default-features = false, features = ["process"] }
reqwest.workspace = true
secrecy.workspace = true
sentry = { version = "0.47", default-features = false, features = [
    "backtrace",
    "panic",
    "reqwest",
    "tracing",
    "rustls",
] }
serde.workspace = true
serde_json.workspace = true
serde_qs.workspace = true
serde_with.workspace = true
shadow-rs.workspace = true
shared-types = { workspace = true, features = ["utoipa"] }
sql-data-provider = { workspace = true, features = ["mysql", "postgres"] }
standardized-types = { workspace = true, features = ["utoipa"] }
strum.workspace = true
thiserror.workspace = true
time.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
tower-http = { version = "0.6", features = ["trace", "catch-panic"] }
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
utoipa = { workspace = true, features = [
    "uuid",
    "axum_extras",
    "url",
    "time",
    "yaml",
    "preserve_path_order",
    "indexmap",
] }
utoipa-swagger-ui = { version = "9.0", features = ["axum"] }
utoipauto = { version = "0.2" }
uuid.workspace = true

[build-dependencies]
serde                = { workspace = true, features = ["derive"] }
serde_json.workspace = true
shadow-rs.workspace  = true

[dev-dependencies]
asn1-rs.workspace          = true
assert2.workspace          = true
async-trait.workspace      = true
ciborium.workspace         = true
hex.workspace              = true
hex-literal.workspace      = true
maplit.workspace           = true
one-core                   = { workspace = true, features = ["config_json", "config_yaml", "config_env", "mock"] }
rand.workspace             = true
rcgen.workspace            = true
reqwest                    = { workspace = true, features = ["json", "form"] }
roxmltree.workspace        = true
sea-orm.workspace          = true
secrecy.workspace          = true
serde_json_path.workspace  = true
serde_urlencoded.workspace = true
similar-asserts.workspace  = true
sql-data-provider          = { workspace = true, features = ["test_utils"] }
ulid.workspace             = true
validator.workspace        = true
wiremock.workspace         = true
x509-parser.workspace      = true

[lints]
workspace = true
